name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
    paths:
      - 'application/**'  # Adjust this path to where your Dockerfile and source code are located

jobs:
  build_and_push:
    name: Build Docker Image and Push to ACR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: <YOUR_ACR_NAME>.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Image
      uses: docker/build-push-action@v2
      with:
        context: ./application  # Adjust this to the path containing your Dockerfile
        file: ./application/Dockerfile
        push: true
        tags: <YOUR_ACR_NAME>.azurecr.io/weather-app:${{ github.sha }}

    - name: Docker Build and Push Complete
      run: echo "Docker image has been successfully built and pushed."
